# Generated by Django 3.2.3 on 2025-07-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipes_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='short_code',
            field=models.CharField(default='eFNg2JT57xRhXHjJYy5nZHmLzDmrkcPkXdFyJg3n1djsDXPSdYETRysU87GCANuQHjc5Y2', max_length=6, unique=True),
        ),
    ]
