# Generated by Django 3.2.3 on 2025-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipes_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='short_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
