# Generated by Django 3.2.3 on 2025-07-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250706_1642'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_recipe_user',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='prevent_recipe_user',
        ),
    ]
