# Generated by Django 3.2.3 on 2025-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250714_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='short_code',
            field=models.CharField(default='kBAzwG', max_length=6, unique=True),
        ),
    ]
