# Generated by Django 3.2.3 on 2025-07-14 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250714_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username содержит недопустимые символы. Допустимы: буквы, цифры, @/./+/-/_', regex='^[\\w.@+-]+\\Z')], verbose_name='Ник-нейм пользователя'),
        ),
    ]
